"""premios

Revision ID: 557cf91eb201
Revises: a0ad832bf5a6
Create Date: 2025-08-25 13:35:18.486391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557cf91eb201'
down_revision = 'a0ad832bf5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('puntos_requeridos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premios')
    # ### end Alembic commands ###
